export const siteConfig = {
  name: "Mikail Nurwahid",
  title: "Mikail Nurwahid — Software Engineer Fullstack Mobile App",
  tagline: "Software Engineer Fullstack Mobile App | AI-Augmented & Offline-First Systems",
  description:
    "Interactive Personal Portfolio & Multimodal ATS-Friendly Resume Engine. Showcasing production-grade engineering feats with verifiable STAR metrics: GreenPay E-Wallet (Offline-First / SQLite / 454 CI Tests), QuranApp (Design System / WCAG 2.1 AA), and Personal Portfolio AI with direct GitHub repository showcases.",
  url: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
  author: {
    name: "Mikail Nurwahid",
    role: "Software Engineer Fullstack Mobile App",
    bio: "Software Engineer (Entry-Level / < 1 tahun pengalaman) dengan keunggulan AI-Augmented Engineering workflow. Terbiasa memadukan fondasi rekayasa perangkat lunak (Clean Architecture, Offline-First SQLite, Automated Testing) dengan akselerasi alat kecerdasan buatan untuk membangun sistem mobile dan backend berskala produksi secara disiplin dan cepat. Berpengalaman merancang sistem dompet digital (GreenPay) dengan 454 automated unit & integration tests (100% CI pass rate), pengamanan biometrik, TOTP 2FA, transaksi AML Maker-Checker dengan Optimistic Concurrency Control, serta aplikasi QuranApp modern berstandar aksesibilitas WCAG 2.1 AA.",
    location: "Jawa Barat, Indonesia",
    availability: "Open for Opportunities & Fullstack Mobile Engineering Roles",
    email: "mikailnurwahid01@gmail.com",
    phone: "+62 838-6004-996",
    github: "https://github.com/Michaelo7710",
    linkedin: "https://github.com/Michaelo7710",
  },
  links: {
    github: "https://github.com/Michaelo7710",
    linkedin: "https://github.com/Michaelo7710",
    greenpayShowcase: "https://github.com/Michaelo7710/greenpay-showcase",
    quranappShowcase: "https://github.com/Michaelo7710/quranapp-showcase",
    portfolioAi: "https://github.com/Michaelo7710/personal-portfolio-ai",
  },
  skills: [
    "React Native & Expo (v57)",
    "TypeScript & Node.js (v22 LTS)",
    "Express.js & Clean Architecture",
    "SQLite Offline-First & MongoDB",
    "Biometric Auth & TOTP 2FA (RFC 6238)",
    "Jest & Automated Testing (454+ Tests)",
    "GitHub Actions CI/CD & Security Auditing",
    "AI-Augmented Engineering & Multimodal LLM Workflows",
  ],
};
